spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/zomo?characterEncoding=utf-8&useSSL=false
    username: root
    password: q1w2e3r4
  jpa:
    show-sql: true